### ISSUE TITLE
getTemporaryCredentials Fails on $client->post()->send()

### ISSUE THREAD

**Issue by kristinaelise** [Y0lk/oauth1-etsy#1]
It seems like `send()` is no longer necessary. Try was failing with:

```
 $response = $client->post($uri, $headers)->send();
```

but succeeds with:

```
$response = $client->post($uri, [ 'headers' => $headers ]);
```

**Comment by Y0lk** [comment]
Sorry for the delay, you're right! Just fixed it, thanks for this. League's client (used by this) was updated to guzzle 6 with their 1.7 update so it totally broke it
